import type { NextPage } from "next";
import Head from "next/head";
import { SearchBar, Table } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Crypton - All you need to know about Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav>
          <p className="nav-title">Crypton Table</p>
        </nav>
        <body className={styles.container}>
          <SearchBar />
          <Table />
        </body>
      </main>
    </div>
  );
};

export default Home;
